volumes:
  minio-storage:
  mongodb_data:

services:
  minio:
    restart: always
    image: minio/minio:latest
    container_name: minio_test
    command: server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001" /data/

    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  mongodb:
    restart: always
    image: mongo:7.0.5
    container_name: mongo_test
    ports:
      - "27027:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  app:
    build:
      dockerfile: Dockerfile
    container_name: python_app
    image: python_app
    env_file:
      .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
